// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/project": {
    params: {};
  };
  "/project/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/project" | "/project/:slug";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/about" | "/project" | "/project/:slug";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/project.tsx": {
    id: "routes/project";
    page: "/project";
  };
  "routes/projectDetails.tsx": {
    id: "routes/projectDetails";
    page: "/project/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/project": typeof import("./app/routes/project.tsx");
  "routes/projectDetails": typeof import("./app/routes/projectDetails.tsx");
};